- set_fact:
    _bytecode_in_lib: true
    _lua_prefix: 'lib'

- include: prepare.yml

- name: register lua files for compilation
  command: find -name *.lua -printf "%P\n"
  register: _lua
  args:
    chdir: "{{ package_path }}/lib"
  when: _bytecode_in_lib|bool

- set_fact:
    _lua_files: "{{ _lua.stdout_lines }}"
  when: _bytecode_in_lib|bool

- name: compile bytecode
  command: >-
    ./luajit -bn {{ item|replace('/', '.')|regex_replace('\.lua$', '') }}
    -s {{ package_path }}/{{ _lua_prefix }}/{{ item }} bytecode/{{ item|replace('/', '_')|regex_replace('\.lua$', '') }}.o
  args:
    chdir: "{{ nginx_build_directory }}"
  with_items: "{{ _lua_files }}"

- name: add lua packages to libluapackages.a
  command: >-
    ar rc {{ luajit_lib_dir }}/libluapackages.a {{ item|replace('/', '_')|regex_replace('\.lua$','') }}.o
  args:
    chdir: "{{ nginx_build_directory }}/bytecode"
  with_items: "{{ _lua_files }}"

- set_fact:
    bytecode_needed: true
